/** Field labels and sheet titles aligned with web (Frontend form labels). */
export const FORM_LABELS = {
  customer: {
    addTitle: 'Add Customer',
    editTitle: 'Edit Customer',
    name: 'Name',
    company: 'Company (optional)',
    email: 'Email (optional)',
    phone: 'Phone (optional)',
    save: 'Save',
    add: 'Add customer',
  },
  product: {
    addTitle: 'Add Product',
    editTitle: 'Edit Product',
    image: 'Product image (optional)',
    name: 'Product Name *',
    sku: 'SKU (optional)',
    barcode: 'Barcode (optional)',
    alternateBarcode: 'Product Code (optional)',
    sellingPrice: 'Selling Price *',
    costPrice: 'Cost Price (optional)',
    quantityOnHand: 'Quantity on Hand',
    create: 'Create Product',
    save: 'Save changes',
    delete: 'Delete',
  },
  variant: {
    detailTitle: 'Variant Details',
    editTitle: 'Edit Variant',
    addTitle: 'Add Variant',
    name: 'Name',
    sku: 'SKU (optional)',
    barcode: 'Barcode (optional)',
    size: 'Size (optional)',
    color: 'Color (optional)',
    model: 'Model (optional)',
    sellingPrice: 'Selling Price *',
    costPrice: 'Cost Price (optional)',
    quantityOnHand: 'Stock',
    save: 'Save changes',
    create: 'Add Variant',
    delete: 'Delete',
    emptyHint: 'No variants yet. Add sizes, colors, models, or other options.',
  },
  expense: {
    addTitle: 'Add Expense',
    category: 'Category',
    amount: 'Amount',
    description: 'Description (optional)',
    expenseDate: 'Expense Date',
    paymentMethod: 'Payment Method (Optional)',
    notes: 'Notes (Optional)',
    record: 'Record Expense',
  },
  lead: {
    addTitle: 'New Lead',
    leadName: 'Lead Name',
    company: 'Company (optional)',
    email: 'Email (optional)',
    phone: 'Phone (optional)',
    source: 'Lead Source (optional)',
    otherSource: 'Other source (optional)',
    save: 'Create Lead',
  },
  task: {
    addTitle: 'Create task',
    title: 'Title',
    description: 'Description (optional)',
    dueDate: 'Due date',
    create: 'Create task',
  },
  cart: {
    selectCustomer: 'Select Customer',
    payment: 'Payment',
    phone: 'Phone',
    nameOptional: 'Name (optional)',
    findOrAdd: 'Find or add customer',
    walkIn: 'Walk-in Customer',
    paymentMethod: 'Payment method',
    amountTendered: 'Amount tendered',
    mobileMoneyNumber: 'Mobile money number',
    completeSale: 'Complete Payment',
    dealerSale: 'Charge to dealer account',
    completeDealerSale: 'Charge to account',
  },
  dealer: {
    addTitle: 'Add Dealer',
    editTitle: 'Edit Dealer',
    businessName: 'Business name *',
    contactName: 'Contact name (optional)',
    email: 'Email (optional)',
    phone: 'Phone (optional)',
    creditLimit: 'Credit limit (optional)',
    openingBalance: 'Opening balance (optional)',
    creditTerms: 'Credit terms (optional)',
    notes: 'Notes (optional)',
    save: 'Save changes',
    add: 'Add dealer',
  },
} as const;
