#!/bin/bash

# Sabito Mobile - Environment Setup Script
# This script helps you quickly set up your environment configuration

echo "🚀 Sabito Mobile - Environment Setup"
echo "===================================="
echo ""

# Check if .env.development already exists
if [ -f .env.development ]; then
    echo "⚠️  .env.development already exists!"
    read -p "Do you want to overwrite it? (y/n): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "❌ Setup cancelled"
        exit 1
    fi
fi

echo "Select your platform:"
echo "1) iOS Simulator (localhost)"
echo "2) Android Emulator (10.0.2.2)"
echo "3) Physical Device (custom IP)"
echo ""
read -p "Enter choice (1-3): " platform

case $platform in
    1)
        echo "📱 Setting up for iOS Simulator..."
        API_URL="http://localhost:4002"
        SUPPORT_URL="http://localhost:5174/api/support/support-content.json"
        ;;
    2)
        echo "📱 Setting up for Android Emulator..."
        API_URL="http://10.0.2.2:4002"
        SUPPORT_URL="http://10.0.2.2:5174/api/support/support-content.json"
        ;;
    3)
        echo "📱 Setting up for Physical Device..."
        echo ""
        echo "Find your local IP:"
        echo "  Mac/Linux: ifconfig | grep 'inet '"
        echo "  Windows: ipconfig"
        echo ""
        read -p "Enter your local IP address (e.g., 192.168.1.5): " LOCAL_IP
        API_URL="http://$LOCAL_IP:4002"
        SUPPORT_URL="http://$LOCAL_IP:5174/api/support/support-content.json"
        ;;
    *)
        echo "❌ Invalid choice"
        exit 1
        ;;
esac

# Create .env.development file
cat > .env.development << EOF
# Sabito Mobile App - Development Environment
# Auto-generated by setup-env.sh

# API Configuration
API_URL=$API_URL

# Support Content URL
SUPPORT_CONTENT_URL=$SUPPORT_URL

# Google OAuth (Update with your credentials)
GOOGLE_CLIENT_ID_IOS=your-ios-client-id.apps.googleusercontent.com
GOOGLE_CLIENT_ID_ANDROID=your-android-client-id.apps.googleusercontent.com
GOOGLE_CLIENT_ID_WEB=your-web-client-id.apps.googleusercontent.com

# Paystack Configuration (Update with your key)
PAYSTACK_PUBLIC_KEY=pk_test_xxxxxxxxxxxxxxxxxx

# Feature Flags
ENABLE_DARK_MODE=true
ENABLE_BIOMETRIC_AUTH=true
ENABLE_PUSH_NOTIFICATIONS=true

# Cache Configuration
SUPPORT_CONTENT_CACHE_HOURS=24
SESSION_TIMEOUT_MINUTES=30

# Debug
DEBUG_MODE=true
LOG_LEVEL=verbose
EOF

echo ""
echo "✅ .env.development created successfully!"
echo ""
echo "📝 Configuration:"
echo "  API URL: $API_URL"
echo "  Support URL: $SUPPORT_URL"
echo ""
echo "Next steps:"
echo "1. Make sure your backend is running on port 4002"
echo "2. Make sure Sabito-website is running on port 5174"
echo "3. Run: npm start --reset-cache"
echo ""
echo "📚 For more details, see QUICK_START.md"
echo ""


