@echo off
REM Sabito Mobile - Environment Setup Script (Windows)
REM This script helps you quickly set up your environment configuration

echo.
echo ========================================
echo Sabito Mobile - Environment Setup
echo ========================================
echo.

REM Check if .env.development already exists
if exist .env.development (
    echo WARNING: .env.development already exists!
    set /p overwrite="Do you want to overwrite it? (y/n): "
    if /i not "%overwrite%"=="y" (
        echo Setup cancelled
        exit /b 1
    )
)

echo Select your platform:
echo 1) iOS Simulator (localhost)
echo 2) Android Emulator (10.0.2.2)
echo 3) Physical Device (custom IP)
echo.
set /p platform="Enter choice (1-3): "

if "%platform%"=="1" (
    echo Setting up for iOS Simulator...
    set API_URL=http://localhost:4002
    set SUPPORT_URL=http://localhost:5174/api/support/support-content.json
) else if "%platform%"=="2" (
    echo Setting up for Android Emulator...
    set API_URL=http://10.0.2.2:4002
    set SUPPORT_URL=http://10.0.2.2:5174/api/support/support-content.json
) else if "%platform%"=="3" (
    echo Setting up for Physical Device...
    echo.
    echo Find your local IP: ipconfig
    echo.
    set /p LOCAL_IP="Enter your local IP address (e.g., 192.168.1.5): "
    set API_URL=http://%LOCAL_IP%:4002
    set SUPPORT_URL=http://%LOCAL_IP%:5174/api/support/support-content.json
) else (
    echo Invalid choice
    exit /b 1
)

REM Create .env.development file
(
echo # Sabito Mobile App - Development Environment
echo # Auto-generated by setup-env.bat
echo.
echo # API Configuration
echo API_URL=%API_URL%
echo.
echo # Support Content URL
echo SUPPORT_CONTENT_URL=%SUPPORT_URL%
echo.
echo # Google OAuth ^(Update with your credentials^)
echo GOOGLE_CLIENT_ID_IOS=your-ios-client-id.apps.googleusercontent.com
echo GOOGLE_CLIENT_ID_ANDROID=your-android-client-id.apps.googleusercontent.com
echo GOOGLE_CLIENT_ID_WEB=your-web-client-id.apps.googleusercontent.com
echo.
echo # Paystack Configuration ^(Update with your key^)
echo PAYSTACK_PUBLIC_KEY=pk_test_xxxxxxxxxxxxxxxxxx
echo.
echo # Feature Flags
echo ENABLE_DARK_MODE=true
echo ENABLE_BIOMETRIC_AUTH=true
echo ENABLE_PUSH_NOTIFICATIONS=true
echo.
echo # Cache Configuration
echo SUPPORT_CONTENT_CACHE_HOURS=24
echo SESSION_TIMEOUT_MINUTES=30
echo.
echo # Debug
echo DEBUG_MODE=true
echo LOG_LEVEL=verbose
) > .env.development

echo.
echo ========================================
echo SUCCESS: .env.development created!
echo ========================================
echo.
echo Configuration:
echo   API URL: %API_URL%
echo   Support URL: %SUPPORT_URL%
echo.
echo Next steps:
echo 1. Make sure your backend is running on port 4002
echo 2. Make sure Sabito-website is running on port 5174
echo 3. Run: npm start --reset-cache
echo.
echo For more details, see QUICK_START.md
echo.
pause


